version: '3.3'
services:
  mongo:
    image: mongo
    container_name: newsmongodb
    volumes:
      - mongo-data:/data/db
    restart: always
    ports:
      - "27017:27017"
  app:
    image: apinews
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    restart: always
    environment:
      MONGO_URL: mongo
volumes:
  mongo-data: {}